Respect PULUMI_HOME (#162)
providertest currently assumes all plugins are installed to
`~/.pulumi/plugins` but a test might run under a different `PULUMI_HOME`
and we should respect that.

This unblocks docker-build workflows currently failing with:
```
--- FAIL: TestNodeExampleUpgrade (1.54s)
panic: expected plugin binary to exist at /home/runner/.pulumi/plugins/resource-docker-build-v0.0.7 [recovered]
	panic: expected plugin binary to exist at /home/runner/.pulumi/plugins/resource-docker-build-v0.0.7
```